- name: install Redis packages
  apt: cache_valid_time={{ apt_cache_seconds }}
       name={{ item }}
       state=latest
       update_cache=yes
  become: true
  with_items:
    - redis-server
  notify:
    - restart redis