- name: add supervisor configuration file for gunicorn
  template: src=plan.service.conf
            dest=/etc/systemd/system/plan.service
  become: true
  notify:
    - restart uwsgi
  tags: uwsgi

- name: database migrate
  django_manage: command=migrate
                 app_path={{ source_directory }}
                 settings={{ settings_name }}
                 virtualenv={{ virtualenv_folder_root }}/current
  environment:
    DB_HOST: localhost
    DB_PORT: 5432
    DB_NAME: "{{ project_name }}"
    DB_USER: "{{ project_name }}"
    DB_PASSWORD: "{{ postgresql_password }}"
    APP_ENV: PRODUCTION
  notify:
    - restart uwsgi

- name: collect static files
  django_manage: command=collectstatic
                 app_path={{ source_directory }}
                 settings={{ settings_name }}
                 virtualenv={{ virtualenv_folder_root }}/current
  environment:
    BASE_DIR: "{{ source_directory }}"
  notify:
    - restart nginx
