- name: add rsyslog config to main app
  template: src=rsyslog.app.conf
            dest=/etc/rsyslog.d/{{ project_name }}.conf
  become: true
  notify:
    - restart rsyslog
    
- name: add rsyslog config to celery app
  template: src=rsyslog.celery.conf
            dest=/etc/rsyslog.d/{{ project_name }}-celery.conf
  become: true
  notify:
    - restart rsyslog