- name: update package list & upgrade existing packages
  apt: cache_valid_time={{ apt_cache_seconds }} update_cache=yes upgrade=yes
  become: true

# Install useful packages:
#   - fail2ban so we can prevent brute force attacks.
#   - logrotate so that any custom server logs get rotated and do not
#     cause us to run out of disk space.
#   - ntp to automatically correct the server's clock if necessary.
#   - unattended-upgrades because installing security updates manually
#     is no fun.
#   - vim because it is better than emacs.
- name: install common packages
  apt: cache_valid_time={{ apt_cache_seconds }}
       name={{ item }}
       state=latest
       update_cache=yes
  become: true
  with_items:
    - fail2ban
    - logrotate
    - ntp
    - unattended-upgrades
    - vim

# Add custom apt configuration file to enable automatic upgrades of
# security updates.
- name: copy apt configuration file for automatic upgrades
  template: src=20auto-upgrades
            dest=/etc/apt/apt.conf.d/20auto-upgrades
  become: true
