# Generated by Django 2.1.2 on 2019-06-25 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('magplan', '0003_post_last_updater'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='author_new',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Новый автор'),
        ),
        migrations.AddField(
            model_name='idea',
            name='author_type',
            field=models.CharField(choices=[('NO', 'Нет автора'), ('NW', 'Новый автор'), ('EX', 'Существующий автор(ы)')], default='NO', max_length=2, verbose_name='Тип автора'),
        ),
        migrations.AddField(
            model_name='idea',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor', to=settings.AUTH_USER_MODEL),
        ),
    ]
