# Generated by Django 2.1.2 on 2019-06-30 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magplan', '0006_auto_20190629_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_at',
            new_name='finished_at',
        ),
    ]
