# Generated by Django 3.1.6 on 2021-03-16 16:00

import django.contrib.sites.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magplan", "0006_auto_20210316_1840"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="post",
            managers=[
                ("objects", django.db.models.manager.Manager()),
                (
                    "on_current_site",
                    django.contrib.sites.managers.CurrentSiteManager(),
                ),
            ],
        ),
    ]
