# Generated by Django 2.1.2 on 2019-06-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magplan', '0007_auto_20190630_1300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('move_post_to_any_stage', 'Can move post to any stage'), ('schedule_publish', 'Can schedule publish'))},
        ),
        migrations.AddField(
            model_name='post',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
