# Generated by Django 2.1.2 on 2019-09-01 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magplan', '0009_auto_20190726_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
    ]
