# Generated by Django 4.2.11 on 2024-04-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magplan", "0011_auto_20210624_1817"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="comment",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="post",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="stage",
            name="meta",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="user",
            name="meta",
            field=models.JSONField(default=dict),
        ),
    ]
