# Generated by Django 4.2.11 on 2024-05-01 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("magplan", "0012_alter_attachment_meta_alter_comment_meta_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SitePreferenceModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=150,
                        null=True,
                        verbose_name="Section Name",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Name"
                    ),
                ),
                (
                    "raw_value",
                    models.TextField(
                        blank=True, null=True, verbose_name="Raw Value"
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="sites.site",
                    ),
                ),
            ],
        ),
    ]
