# Generated by Django 2.2 on 2020-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magplan', '0012_auto_20200814_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='css',
            field=models.TextField(help_text='CSS, который будет применяться к превью статьи, а также будет использоваться при загрузке во вншение CMS.', null=True, verbose_name='CSS-стили для статьи'),
        ),
    ]
