# Generated by Django 2.1.2 on 2019-01-16 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('manage_authors', 'Can manage authors'),)},
        ),
    ]
