# Generated by Django 2.1.2 on 2019-06-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190626_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='author_new',
            new_name='authors_new',
        ),
    ]
