# Generated by Django 2.1.2 on 2019-06-29 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190628_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='authors',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='authors_new',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Новые автор'),
        ),
    ]
