# Generated by Django 2.1.2 on 2019-07-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190630_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'permissions': (('edit_extended_idea_attrs', 'Edit extended Idea attributes'), ('recieve_idea_email_updates', 'Recieve email updates for Idea'))},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('recieve_post_email_updates', 'Recieve email updates for Post'), ('edit_extended_post_attrs', 'Edit extended Post attributes'))},
        ),
        migrations.AlterField(
            model_name='idea',
            name='author_type',
            field=models.CharField(choices=[('NO', 'Нет автора'), ('NW', 'Новый автор'), ('EX', 'Существующий автор(ы)')], default='NO', max_length=2, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
    ]
