# Generated by Django 2.2 on 2020-08-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20191227_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='score',
            field=models.SmallIntegerField(choices=[(0, 'Против таких статей в «Хакере»'), (25, 'Не верю, что выйдет хорошо'), (50, 'Тема нормальная, но не для меня'), (75, 'Почитал бы, встретив в журнале'), (100, 'Ради таких статей мог бы подписаться')], default=50),
        ),
    ]
