# Delete virtualenvs that are linked to "current" or "previous".
# Generally, this will be one virtualenv (the one that was linked to
# "previous" before the deployment).
- name: delete other virtualenvs
  shell: find  -maxdepth 1
         ! -path '.'
         ! -path './'$(basename $(readlink current))
         ! -path './'$(basename $(readlink previous))
         -type d -exec rm -rf {} +
  args:
    chdir: "{{ virtualenv_folder_root }}"
