# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: post.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npost.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb4\x02\n\x04Post\x12\x0f\n\x02id\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04lead\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x19\n\x0chtml_content\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x16\n\x0e\x61uthors_emails\x18\x05 \x03(\t\x12\x19\n\x0cis_published\x18\x06 \x01(\x08H\x04\x88\x01\x01\x12\x15\n\x08issue_id\x18\x07 \x01(\x05H\x05\x88\x01\x01\x12\x35\n\x0cpublished_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x06\x88\x01\x01\x42\x05\n\x03_idB\x08\n\x06_titleB\x07\n\x05_leadB\x0f\n\r_html_contentB\x0f\n\r_is_publishedB\x0b\n\t_issue_idB\x0f\n\r_published_atb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_POST']._serialized_start=48
  _globals['_POST']._serialized_end=356
# @@protoc_insertion_point(module_scope)
